spring:
  application:
    # UNIQUE NAME OF THIS MICROSERVICE
    name: airport-security-service
  # ANSI CONSOLE OUTPUT (COLOR LOGS WILL BE DISPLAYED)
  output:
    ansi:
      enabled: ALWAYS
  # DATABASE CREDENTIALS
  datasource:
    url: 'jdbc:mysql://mysql:3306/airportdb'
    username: airportuser
    password: airportpass
  # ZIPKIN SERVER URL
  zipkin:
    base-url: 'http://zipkin:9411'

server:
  # TO RUN THIS MICROSERVICE ON RANDOM SERVER PORT 'server.port=0'
  # SERVER PORT OF THIS MICROSERVICE
  port: '8084'

# EUREKA SERVER URL
eureka:
  client:
    service-url:  # Changed from 'service.url' to 'service-url'
      defaultZone: 'http://eureka-server:8761/eureka'
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: airport-security-service
    instance-id: ${spring.application.name}:${server.port}

# SWAGGER-UI CUSTOM PATH
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# ACTUATOR WEB ENDPOINTS EXPOSURE
management:
  endpoints:
    web:
      exposure:
        # EXPOSE ALL THE ACTUATOR WEB ENDPOINTS IF SECURITY IS NOT YOUR CONCERN!
        include: "*"
  # GET DETAIL INFORMATION OF ACTUATOR HEALTH ENDPOINT 
  endpoint:    
    health:
      show-details: always
